language: java
branches:
  only:
  - master
  except:
  - nightly
os: linux
dist: trusty
jdk: oraclejdk8
services:
  - docker
before_install:
  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update
script:
  - ./one_step_mvn_package_docker_build.sh
  - ./start.sh
