language: java
branches:
  only:
  - master
  except:
  - nightly
os: linux
dist: trusty
jdk: oraclejdk8
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- sudo apt-get update
script:
- "./one_step_mvn_package_docker_build.sh"
