language: java
env:
  DOCKER_COMPOSE_VERSION: 1.23.2
branches:
  only:
  - master
  except:
  - nightly
os:  linux
  dist: bionic
jdk: oraclejdk8
services:
  - docker
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
script:
  - mvn test
  - ./one_step_mvn_package_docker_build.sh
  - ./start.sh

# If the `script` job fails, it will send a failure message to Teams channel
after_failure:
  - export TITLE="Travis:$TRAVIS_JOB_ID -- build job is failed"
  - export TEXT=[datetime]:`date`