version: "3"
services:
  zookeeper:
      image: zookeeper
      ports:
        - "2181"
      networks:
        - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend
#    deploy:
#      replicas: 2
#      update_config:
#        parallelism: 2
#        delay: 10s
#      restart_policy:
#        condition: on-failure

  cache:
    image: jylkelvin/disseckill-cache:latest
    ports:
      - "9095:9095"
    command: ["/cache_start.sh"]
    volumes:
      - "/tmp/seckill-cache-log:/tmp/seckill-cache-log"
    networks:
      - backend
    depends_on:
      - redis
      - zookeeper

  mq:
    image: jylkelvin/disseckill-mq:latest
    ports:
      - "9090"
    volumes:
      - "/tmp/seckill-mq-log:/tmp/seckill-mq-log"
    command: ["/mq_start.sh"]
    networks:
      - backend
    depends_on:
      - rabbitmq

  order:
    image: jylkelvin/disseckill-order:latest
    ports:
      - "8080:9091"
    volumes:
      - "/tmp/seckill-order-log:/tmp/seckill-order-log"
    command: ["/order_start.sh"]
    networks:
      - backend
    depends_on:
      - mq
      - cache
networks:
  frontend:
  backend:
